### PR TITLE
Make cmd_lists_count public in DrawData struct

### PR DESCRIPTION
**Pull request by filnet**
Also updated comments with latest from imgui.

Relates to https://github.com/Gekkio/imgui-rs/issues/325

### CODE REVIEW

**Comment by aloucks** [comment]
This should probably be a getter method instead. Making it public allows the value to be mutated which makes `draw_lists()` unsafe: 

```rust
    pub fn draw_lists(&self) -> DrawListIterator {
        unsafe {
            DrawListIterator {
                iter: self.cmd_lists().iter(),
            }
        }
    }
    pub(crate) unsafe fn cmd_lists(&self) -> &[*const DrawList] {
        slice::from_raw_parts(
            self.cmd_lists as *const *const DrawList,
            self.cmd_lists_count as usize,
        )
    }
```

**Comment by filnet** [comment]
Changed to a setter as requested.

**Comment by aloucks** [comment]
cc @Gekkio

**Comment by Gekkio** [comment]
Thanks! :smile: 

Would it make more sense to return `usize` instead of `i32`? The public count fields are `i32` to match the underlying memory layout, but in a getter function we have the option of casting the value to something more appropriate for Rust code. Note also that you can already get the count with `draw_lists().count()`, which returns `usize`.

**Comment by filnet** [comment]
Changed getter to return usize instead of u32.

**Pull request merged**
