### PR TITLE
Update glutin and dependencies that rely on it

### PR DESCRIPTION
**Pull request by brendanzab**
I tried to also make the gfx and glutin support modules more consistent in the examples.

### CODE REVIEW

**Comment by brendanzab** [comment]
Hmm, seems like `wayland-client` doesn't like 1.16. 🤔

**Comment by Gekkio** [comment]
Thanks!

I suppose we'll have to bump the minimum version in `travis.yml` and `README.markdown` :disappointed: 
I'd prefer offering better backwards compatibility, but there's not much we can do if dependencies aggressively use features available only in recent Rust versions. It's not even the first time I've had to bump the minimum Rust version because of `wayland-client`.

**Comment by brendanzab** [comment]
done :(

**Comment by Gekkio** [comment]
Thanks! :) :( :)

**Comment by brendanzab** [comment]
Probably would be a good idea to release this as soon as you're able because it's blocking our work on mac OS.

**Comment by Gekkio** [comment]
0.0.15 is here :tada:

**Pull request merged**
