### PR TITLE
Improve string handling and add more widgets

### PR DESCRIPTION
**Pull request by bjz**
Replaces `im_str!` in favour of using `Into` trait, and adds support for `Ui::{button, invisible_button, progress_bar}`.

### CODE REVIEW

**Comment by bjz** [comment]
Weird... for nightly and beta: https://travis-ci.org/Gekkio/imgui-rs/jobs/117204435#L189

```
no matching package named `imgui-sys` found (required by `imgui`)
```

**Comment by Gekkio** [comment]
Thanks!

Unfortunately, I'm not fond of changing everything to use Into in that way. Please check out #7 for thorough discussion about string handling. While Into still retains the possibility of using the im_str! macro and other zero-overhead methods, in practice everyone will just use normal strings if the into() call is moved from user code to the library code. This makes the macro pointless, and encourages bad practice. There's two solutions that are from my point of view acceptable:

* adding the null terminator at compile-time using constexpr or similar feature once Rust has it in the future
* changing dear imgui itself. A such fork exists, but I haven't made a decision yet to use it. The decision is complicated, because a fork without a proper test suite would significantly increase the risk of having subtle but deadly bugs, and would require active maintaining. So far it looks good, but I'm not ready to make the leap yet.

The new widgets look good! I noticed just one thing: progress bar should be usable without an overlay.
In the original API you can pass a null pointer, so we should either use Option or use the builder pattern as used in other places in this library.

The build failure in nightly and beta seems to be caused by the combination of using a version and a path in Cargo.toml. I'll see if I can figure out how to fix it properly, so don't worry about it.

**Comment by bjz** [comment]
Dang, that's a shame. I guess seeing as complex UIs could be using text heavily, performance is a concern. Hopefully string views become part of imgui in the future!

**Comment by bjz** [comment]
Perhaps it would be good to add the reasoning behind `im_str!` in the readme?

**Comment by bitshifter** [comment]
@bjz FYI my fork which removes the need for im_str! while avoiding string copies is here https://github.com/bitshifter/imgui-rs/tree/imstr

**Comment by bjz** [comment]
Nice! :)

**Comment by Gekkio** [comment]
Sorry, I should've linked the fork here since I mentioned it.

> Perhaps it would be good to add the reasoning behind im_str! in the readme?

That's a good idea! It's a significant source for confusion, so I'll mention it in the readme.

In any case, since compile-time functions in Rust seem to be a bit far off, I think I'll probably switch to bitshifter's imgui/cimgui forks soon once I manage to create a basic test suite in this project.

**Comment by bjz** [comment]
That would be super nice from a UX point of view! <3

**Pull request closed without merging**
